image: docker.pkg.github.com/s2shape/docker-images/s2shape-test-harness:latest

stages:
  - build
  - test

variables:
  DYNAMODB_HOST: dynamo
  DYNAMODB_PORT: "8000"
  AWS_ACCESS_KEY_ID: "key_id"
  AWS_SECRET_ACCESS_KEY: "access_key"

before_script:
  - dotnet restore -s https://www.myget.org/F/s2/ -s https://api.nuget.org/v3/index.json

build:
  stage: build
  script:
    - cd DynamoDbSupplyCollector
    - dotnet restore
    - dotnet build

test:
  stage: test

  services:
    - name: instructure/dynamo-local-admin
      alias: dynamo

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/DynamoDbSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init DynamoDbSupplyCollector "ServiceURL=http://$DYNAMODB_HOST:$DYNAMODB_PORT;AccessKey=$AWS_ACCESS_KEY_ID;AccessSecret=$AWS_SECRET_ACCESS_KEY"
    - dotnet SupplyCollectorDataLoader.dll -xunit DynamoDbSupplyCollector "ServiceURL=http://$DYNAMODB_HOST:$DYNAMODB_PORT;AccessKey=$AWS_ACCESS_KEY_ID;AccessSecret=$AWS_SECRET_ACCESS_KEY"
    - cd $ROOT_PROJECT_PATH
    - dotnet test

load_test:
  stage: test
  services:
    - name: instructure/dynamo-local-admin
      alias: dynamo

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/DynamoDbSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init DynamoDbSupplyCollector "ServiceURL=http://$DYNAMODB_HOST:$DYNAMODB_PORT;AccessKey=$AWS_ACCESS_KEY_ID;AccessSecret=$AWS_SECRET_ACCESS_KEY"
    - dotnet SupplyCollectorDataLoader.dll -xunit DynamoDbSupplyCollector "ServiceURL=http://$DYNAMODB_HOST:$DYNAMODB_PORT;AccessKey=$AWS_ACCESS_KEY_ID;AccessSecret=$AWS_SECRET_ACCESS_KEY"
    - dotnet SupplyCollectorDataLoader.dll -samples DynamoDbSupplyCollector "ServiceURL=http://$DYNAMODB_HOST:$DYNAMODB_PORT;AccessKey=$AWS_ACCESS_KEY_ID;AccessSecret=$AWS_SECRET_ACCESS_KEY" TestCollection Test1:int,Test2:string,Test3:bool,Test4:double,Test5 1000000
    - cd $ROOT_PROJECT_PATH/DynamoDbSupplyCollectorTests/bin/Debug/netcoreapp2.2/publish
    - SupplyCollectorTestHarness
