version: "3"

services:
  
  dynamo:
    image: "instructure/dynamo-local-admin"
    ports:
    - "8000:8000"
    networks: 
    - supply-collector
  
  dynamoinit:
    build: ./DynamoInit
    environment:
      AWS_ACCESS_KEY_ID: "key_id"
      AWS_SECRET_ACCESS_KEY: "access_key"
    depends_on:
      - "dynamo"
    networks: 
    - supply-collector

networks:
  supply-collector: 
    driver: bridge
    